from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(name='Audit', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('name', models.CharField(max_length=200)), ('date', models.DateField()), ('scope', models.CharField(max_length=300)), ('auditor', models.CharField(max_length=120)), ('findings', models.TextField(blank=True)), ('status', models.CharField(default='draft', max_length=15))]),
        migrations.CreateModel(name='Department', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('name', models.CharField(max_length=120)), ('code', models.CharField(max_length=30, unique=True)), ('governance_score', models.DecimalField(decimal_places=2, default=100, max_digits=5))]),
        migrations.CreateModel(name='Policy', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('title', models.CharField(max_length=200)), ('content', models.TextField()), ('version', models.CharField(max_length=30)), ('effective_date', models.DateField()), ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=10))]),
        migrations.CreateModel(name='ComplianceIssue', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)), ('description', models.TextField()), ('due_date', models.DateField()), ('status', models.CharField(default='open', max_length=10)), ('resolved_at', models.DateTimeField(blank=True, null=True)), ('created_at', models.DateTimeField(auto_now_add=True)), ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='governance.audit')), ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='governance.department')), ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_issues', to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name='PolicyAcknowledgement', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('acknowledged_at', models.DateTimeField(auto_now_add=True)), ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)), ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgements', to='governance.policy'))], options={'unique_together': {('policy', 'employee')}}),
        migrations.CreateModel(name='Notification', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('message', models.CharField(max_length=300)), ('kind', models.CharField(max_length=50)), ('created_at', models.DateTimeField(auto_now_add=True)), ('read_at', models.DateTimeField(blank=True, null=True)), ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='governance.complianceissue')), ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL))]),
    ]
