# Generated by Django 4.2.3 on 2026-07-12 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernanceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.CharField(choices=[('JAN', 'January'), ('FEB', 'February'), ('MAR', 'March'), ('APR', 'April'), ('MAY', 'May'), ('JUN', 'June'), ('JUL', 'July'), ('AUG', 'August'), ('SEP', 'September'), ('OCT', 'October'), ('NOV', 'November'), ('DEC', 'December')], max_length=3)),
                ('board_members', models.PositiveIntegerField()),
                ('independent_directors', models.PositiveIntegerField()),
                ('audit_score', models.FloatField(help_text='Audit score (0-100)')),
                ('compliance_score', models.FloatField(help_text='Compliance score (0-100)')),
                ('ethics_training_percentage', models.FloatField(help_text='Percentage (0-100)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='governance_records', to='companies.company')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('company', 'year', 'month')},
            },
        ),
    ]
