# Generated by Django 4.2.3 on 2026-07-12 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.CharField(choices=[('JAN', 'January'), ('FEB', 'February'), ('MAR', 'March'), ('APR', 'April'), ('MAY', 'May'), ('JUN', 'June'), ('JUL', 'July'), ('AUG', 'August'), ('SEP', 'September'), ('OCT', 'October'), ('NOV', 'November'), ('DEC', 'December')], max_length=3)),
                ('electricity', models.FloatField(help_text='Electricity consumption (kWh)')),
                ('water', models.FloatField(help_text='Water consumption (Liters)')),
                ('fuel', models.FloatField(help_text='Fuel consumption (Liters)')),
                ('waste', models.FloatField(help_text='Waste generated (Kg)')),
                ('co2_emissions', models.FloatField(help_text='CO₂ emissions (Tons)')),
                ('renewable_energy', models.FloatField(help_text='Renewable energy used (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environmental_records', to='companies.company')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('company', 'year', 'month')},
            },
        ),
    ]
